import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { defineComponent } from 'vue';
import { mount } from '@vue/test-utils';
import { vLongpress } from '@/core/directives/longpress';
import ContextMenuSheet from '@/components/ui/ContextMenuSheet.vue';

function mountLongpressButton(
  longpress: () => void,
  click: () => void,
  suppressClick: boolean,
) {
  const component = defineComponent({
    setup: () => ({ longpress, click }),
    template: suppressClick
      ? '<button v-longpress.suppress-click="longpress" @click="click">theme</button>'
      : '<button v-longpress="longpress" @click="click">theme</button>',
  });

  return mount(component, {
    global: { directives: { longpress: vLongpress } },
  });
}

describe('longpress presentation shortcut', () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-08-13T12:00:00Z'));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('fires at 600ms and consumes only the synthetic click after a successful longpress', async () => {
    const longpress = vi.fn();
    const click = vi.fn();
    const wrapper = mountLongpressButton(longpress, click, true);
    const button = wrapper.get('button');

    await button.trigger('touchstart');
    vi.advanceTimersByTime(599);
    expect(longpress).not.toHaveBeenCalled();
    vi.advanceTimersByTime(1);
    expect(longpress).toHaveBeenCalledTimes(1);

    await button.trigger('touchend');
    await button.trigger('click');
    expect(click).not.toHaveBeenCalled();

    await button.trigger('click');
    expect(click).toHaveBeenCalledTimes(1);
    wrapper.unmount();
  });

  it('keeps normal click behavior when the suppress modifier is absent', async () => {
    const longpress = vi.fn();
    const click = vi.fn();
    const wrapper = mountLongpressButton(longpress, click, false);
    const button = wrapper.get('button');

    await button.trigger('touchstart');
    vi.advanceTimersByTime(600);
    await button.trigger('touchend');
    await button.trigger('click');

    expect(longpress).toHaveBeenCalledTimes(1);
    expect(click).toHaveBeenCalledTimes(1);
    wrapper.unmount();
  });

  it('cancels on movement and ignores a non-primary mouse button', async () => {
    const longpress = vi.fn();
    const wrapper = mountLongpressButton(longpress, vi.fn(), true);
    const button = wrapper.get('button');

    await button.trigger('touchstart');
    await button.trigger('touchmove');
    vi.advanceTimersByTime(700);
    expect(longpress).not.toHaveBeenCalled();

    await button.trigger('mousedown', { button: 2 });
    vi.advanceTimersByTime(700);
    expect(longpress).not.toHaveBeenCalled();
    wrapper.unmount();
  });

  it('cancels pending presses on touch cancellation and pointer leave', async () => {
    const longpress = vi.fn();
    const wrapper = mountLongpressButton(longpress, vi.fn(), true);
    const button = wrapper.get('button');

    await button.trigger('touchstart');
    await button.trigger('touchcancel');
    vi.advanceTimersByTime(700);

    await button.trigger('mousedown', { button: 0 });
    await button.trigger('mouseleave');
    vi.advanceTimersByTime(700);

    expect(longpress).not.toHaveBeenCalled();
    wrapper.unmount();
  });

  it('deduplicates the timer and contextmenu generated by one touch gesture', async () => {
    const longpress = vi.fn();
    const wrapper = mountLongpressButton(longpress, vi.fn(), true);
    const button = wrapper.get('button');

    await button.trigger('touchstart');
    vi.advanceTimersByTime(600);
    await button.trigger('contextmenu');

    expect(longpress).toHaveBeenCalledTimes(1);
    wrapper.unmount();
  });
});

describe('ContextMenuSheet selection semantics', () => {
  it('renders selected actions as an accessible radio group with a visible check', async () => {
    const selectedHandler = vi.fn();
    const wrapper = mount(ContextMenuSheet, {
      props: {
        isOpen: true,
        title: '消息呈现',
        actions: [
          { label: '气泡', selected: true, handler: selectedHandler },
          { label: '统一', selected: false, handler: vi.fn() },
          { label: '刊物', selected: false, handler: vi.fn() },
        ],
      },
      global: { stubs: { Teleport: true }, directives: { guide: {} } },
    });

    expect(wrapper.get('[role="radiogroup"]').attributes('aria-label')).toBe('消息呈现');
    const radios = wrapper.findAll('[role="radio"]');
    expect(radios).toHaveLength(3);
    expect(radios[0].attributes('aria-checked')).toBe('true');
    expect(radios[0].attributes('data-selected')).toBe('true');
    expect(radios[0].find('.presentation-check').exists()).toBe(false);
    expect(radios[0].find('polyline').exists()).toBe(true);

    await radios[0].trigger('click');
    expect(selectedHandler).toHaveBeenCalledTimes(1);
    expect(wrapper.emitted('action-click')).toHaveLength(1);
  });

  it('renders and dispatches an optional selected header action', async () => {
    const headerHandler = vi.fn();
    const wrapper = mount(ContextMenuSheet, {
      props: {
        isOpen: true,
        title: 'Topic Options',
        actions: [{ label: '修改标题', handler: vi.fn() }],
        headerAction: {
          label: '取消置顶',
          selected: true,
          handler: headerHandler,
        },
      },
      global: { stubs: { Teleport: true }, directives: { guide: {} } },
    });

    const headerAction = wrapper.get('button[aria-pressed="true"]');
    expect(headerAction.text()).toContain('取消置顶');
    await headerAction.trigger('click');
    expect(headerHandler).toHaveBeenCalledTimes(1);
    expect(wrapper.emitted('header-action-click')).toHaveLength(1);
  });
});
