package com.vcp.mobile.contract

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class PluginContractTest {
    private val pluginRoot = findPluginRoot()

    private fun findPluginRoot(): File {
        var dir = File(System.getProperty("user.dir") ?: ".").canonicalFile
        repeat(8) {
            val direct = File(dir, "src-tauri/plugins/vcp-mobile")
            if (File(direct, "src/lib.rs").exists()) {
                return direct
            }

            val androidModule = File(dir, "src/lib.rs")
            if (androidModule.exists() && File(dir, "guest-js/index.ts").exists()) {
                return dir
            }

            dir = dir.parentFile ?: return@repeat
        }
        error("无法定位 tauri-plugin-vcp-mobile 根目录，user.dir=${System.getProperty("user.dir")}")
    }

    @Test
    fun registeredCommandsCloseTheBuildPermissionAndGuestContracts() {
        val libRs = File(pluginRoot, "src/lib.rs").readText()
        val buildRs = File(pluginRoot, "build.rs").readText()
        val defaultToml = File(pluginRoot, "permissions/default.toml").readText()
        val allToml = File(pluginRoot, "permissions/all.toml").readText()
        val guestJs = File(pluginRoot, "guest-js/index.ts").readText()

        val registeredCommands = Regex("(?:screen|stream|system)::([a-zA-Z0-9_]+)")
            .findAll(libRs)
            .map { it.groupValues[1] }
            .toSet()

        val registrationSurfaces = mapOf(
            "build.rs" to buildRs,
            "permissions/default.toml" to defaultToml,
            "permissions/all.toml" to allToml,
        )
        registrationSurfaces.forEach { (path, source) ->
            val missing = registeredCommands.filter { command ->
                !source.contains("\"$command\"")
            }
            assertTrue("$path 缺少插件命令: $missing", missing.isEmpty())
        }

        val guestCommands = Regex("plugin:vcp-mobile\\|([a-zA-Z0-9_]+)")
            .findAll(guestJs)
            .map { it.groupValues[1] }
            .toSet()
        val unregisteredGuestCommands = guestCommands - registeredCommands
        assertTrue(
            "guest-js 暴露了未注册命令: $unregisteredGuestCommands",
            unregisteredGuestCommands.isEmpty(),
        )
    }

    @Test
    fun dormantAssistantBridgesRemainSourceOnlyAndUnregistered() {
        val systemRs = File(pluginRoot, "src/system.rs").readText()
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val pluginManifest = File(pluginRoot, "android/src/main/AndroidManifest.xml").readText()
        val exposureFiles = listOf(
            "src/lib.rs",
            "build.rs",
            "permissions/default.toml",
            "permissions/all.toml",
        ).associateWith { File(pluginRoot, it).readText() }
        val dormantCommands = listOf("request_overlay_permission", "toggle_floating_ball")

        assertTrue(
            "Rust 技术资产应保留",
            dormantCommands.all { systemRs.contains("pub fn $it") },
        )
        assertTrue(
            "Kotlin 技术资产应保留",
            kotlinPlugin.contains("fun requestOverlayPermission(") &&
                kotlinPlugin.contains("fun toggleFloatingBall("),
        )
        assertTrue(
            "通用权限检查不得实例化或读取休眠的悬浮窗资产",
            !kotlinPlugin.contains("hasOverlayPermission(") &&
                !kotlinPlugin.contains("result.put(\"overlay\"") &&
                !systemRs.contains("pub overlay:"),
        )
        assertTrue(
            "休眠功能不得继续声明悬浮窗权限",
            !pluginManifest.contains("android.permission.SYSTEM_ALERT_WINDOW"),
        )
        dormantCommands.forEach { command ->
            exposureFiles.forEach { (path, content) ->
                assertTrue("$path 不得继续暴露 $command", !content.contains(command))
            }
            assertTrue(
                "注销命令后必须删除 autogenerated permission: $command",
                !File(pluginRoot, "permissions/autogenerated/commands/$command.toml").exists(),
            )
        }
    }

    @Test
    fun guestJsStopStreamServicePassesAgentNameArgument() {
        val guestJs = File(pluginRoot, "guest-js/index.ts").readText()

        assertTrue(
            "stopStreamService 应接收 agentName 参数",
            Regex("function\\s+stopStreamService\\s*\\(\\s*agentName\\s*:\\s*string\\s*\\)").containsMatchIn(guestJs),
        )
        assertTrue(
            "stopStreamService invoke 应传递 { agentName }",
            guestJs.contains("plugin:vcp-mobile|stop_streaming_service") && guestJs.contains("{ agentName }"),
        )
    }

    @Test
    fun nativeFileBridgeKeepsViewAndAddsReadOnlySystemShare() {
        val rustSystem = File(pluginRoot, "src/system.rs").readText()
        val guestJs = File(pluginRoot, "guest-js/index.ts").readText()
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()

        assertTrue(
            "guest-js 应暴露独立的 shareFileNative API",
            guestJs.contains("function shareFileNative(path: string)") &&
                guestJs.contains("{ path, action: 'share' }"),
        )
        assertTrue(
            "Rust 桥接只允许 view/share 两种动作",
            rustSystem.contains("action != \"view\" && action != \"share\"") &&
                rustSystem.contains("\"action\": action"),
        )
        assertTrue(
            "Android 分享必须使用 ACTION_SEND、EXTRA_STREAM 与临时读取授权",
            kotlinPlugin.contains("Intent(Intent.ACTION_SEND)") &&
                kotlinPlugin.contains("Intent.EXTRA_STREAM") &&
                kotlinPlugin.contains("ClipData.newRawUri") &&
                kotlinPlugin.contains("Intent.FLAG_GRANT_READ_URI_PERMISSION"),
        )
        assertTrue(
            "既有 ACTION_VIEW 行为必须保留",
            kotlinPlugin.contains("Intent(Intent.ACTION_VIEW)"),
        )
    }

    @Test
    fun rustRunMobilePluginMethodNamesExistInKotlinPlugin() {
        val rustSources = listOf("src/system.rs", "src/stream.rs", "src/cli.rs")
            .map { File(pluginRoot, it).readText() }
            .joinToString("\n")
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()

        val methodNames = Regex("run_mobile_plugin(?:::<[^>]+>)?\\(\\s*\"([A-Za-z0-9_]+)\"")
            .findAll(rustSources)
            .map { it.groupValues[1] }
            .toSet()

        val missing = methodNames.filter { method ->
            !Regex("fun\\s+$method\\s*\\(").containsMatchIn(kotlinPlugin)
        }

        assertTrue("Rust run_mobile_plugin 方法在 Kotlin 中不存在: $missing", missing.isEmpty())
    }

    @Test
    fun rustMobilePluginCallsDoNotHoldHandleMutexWhileWaitingForKotlin() {
        val libRs = File(pluginRoot, "src/lib.rs").readText()
        val commandSources = listOf("src/system.rs", "src/stream.rs", "src/cli.rs")
            .map { File(pluginRoot, it).readText() }
            .joinToString("\n")

        assertTrue("PluginHandle 必须在锁内 clone", libRs.contains(".as_ref()\n            .cloned()"))
        assertTrue("command 必须通过短锁 helper 获取句柄", commandSources.contains("mobile_plugin_handle()?"))
        assertTrue("command 不得直接持锁跨 run_mobile_plugin", !commandSources.contains("plugin_handle.lock()"))
    }

    @Test
    fun cliProcessHostBridgeIsInternalAndCannotBypassRustJobOwner() {
        val rustCli = File(pluginRoot, "src/cli.rs").readText()
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val processHost = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/cli/CliProcessHost.kt",
        ).readText()
        val publicSurfaces = listOf(
            "src/lib.rs",
            "build.rs",
            "permissions/default.toml",
            "permissions/all.toml",
            "guest-js/index.ts",
        ).associateWith { File(pluginRoot, it).readText() }
        val internalMethods = listOf(
            "prepareCliRuntime",
            "startCliProcess",
            "inspectCliProcess",
            "cancelCliProcess",
            "openCliPty",
            "readCliPty",
            "writeCliPty",
            "resizeCliPty",
            "closeCliPty",
        )
        val internalRustFunctions = listOf(
            "prepare_cli_runtime_inner",
            "start_cli_process_inner",
            "inspect_cli_process_inner",
            "cancel_cli_process_inner",
            "open_cli_pty_inner",
            "read_cli_pty_inner",
            "write_cli_pty_inner",
            "resize_cli_pty_inner",
            "close_cli_pty_inner",
        )

        internalMethods.forEach { method ->
            assertTrue("Rust internal bridge 缺少 method $method", rustCli.contains("\"$method\""))
            assertTrue("Kotlin thin delegate 缺少 $method", kotlinPlugin.contains("fun $method("))
            publicSurfaces.forEach { (path, content) ->
                assertTrue("$path 不得公开内部 CLI method $method", !content.contains(method))
            }
        }
        internalRustFunctions.forEach { function ->
            assertTrue(
                "Rust CLI bridge 缺少 $function",
                rustCli.contains("pub async fn $function") || rustCli.contains("    $function,"),
            )
            assertTrue("内部 bridge 不得成为 #[tauri::command]", !rustCli.contains("#[tauri::command]\npub async fn $function"))
        }
        assertFalse("Kotlin plugin 不应再注册本地语义资产 bridge", kotlinPlugin.contains("prepareCliSemanticAssets"))
        assertTrue("CLI ProcessHost 不得调用 Root/libsu", !processHost.contains("libsu") && !processHost.contains("Shell.getShell"))
        assertTrue("CLI ProcessHost 必须以精确 Job lease 接入 Guardian", processHost.contains("CliNotificationTarget"))
        assertTrue("CLI ProcessHost 必须由应用进程 singleton 持有", processHost.contains("object CliProcessHostOwner"))
        assertTrue("CLI ProcessHost 不得新增 localhost bridge", !processHost.contains("ServerSocket") && !processHost.contains("localhost"))
        assertTrue("plugin onDestroy 不得终止应用进程所有 CLI Job", !kotlinPlugin.contains("cliProcessHost.close()"))
        assertTrue("plugin 必须从应用进程 owner 获取 CLI ProcessHost", kotlinPlugin.contains("CliProcessHostOwner.get(activity.applicationContext)"))
        assertTrue("人工 PTY 必须由独立 owner 持有", kotlinPlugin.contains("CliPtyHostOwner.get(cliProcessHost)"))
    }

}
